### ISSUE TITLE
source_command_wrapper should fail loudly

### ISSUE THREAD

**Issue by rweng** [rvm/rvm-gem#6]
Hi guys,

I've spend my morning tracking down an error in [chef-rvm](https://github.com/fnichol/chef-rvm). It was caused by wrong permission rights on the command_wrapper, due to which it could not be sourced.

Tracking down this error was quite hard, mainly because [source_command_wrapper](https://github.com/wayneeseguin/rvm-gem/blob/master/lib/rvm/shell/abstract_wrapper.rb#L111) failed silently. As far as I see it, the rvm-gem cannot function without the wrapper, is this correct? If so, I suggest to make it raise an exception if errors occur during sourcing.

What do you think?

Robin

**Comment by mpapis** [comment]
@rweng It would be best if we would raise proper exceptions in that cases, unfortunately there are two issues:
1. there is to much self shell handling instead of using external solutions like session gem
2. we do not have tests for it - so it's hard to tell if we do not break anything

We will be adding tests and updating the code for rvm2, I'm not sure how much effort should we put into it in rvm1.

Please feel free to add tests and example implementation if you have time for it, I will be happy to review your pull request.

Thanks,
Michal

**Comment by rweng** [comment]
I lack time to dig deeper into this, but for anyone who is interested: the `run_silently` itself does throw an exception. Rather, the error is raised [in line 136](https://github.com/wayneeseguin/rvm-gem/blob/master/lib/rvm/shell/abstract_wrapper.rb#L136) during the check of `command_complete?`. Since the source_command_wrapper is not loaded, the epilog is missing and the `IncompleteCommandError` is thrown.

**Comment by mpapis** [comment]
by any chance does #12 is related?

**Comment by mpapis** [comment]
closing this as `rvm-gem` will be part of RVM 2.0 and it will itself be part of the API. Here is plan for RVM 2.0 => https://docs.google.com/document/d/1xW9GeEpLOWPcddDg_hOPvK4oeLxJmU3Q5FiCNT7nTAc/edit?usp=sharing
